### ISSUE TITLE
Import DSL/JSON file

### ISSUE THREAD

**Issue by tsauvajon** [goadesign/model#21]
## Context

Hi!

I started using Structurizr and really like the Structurizr DSL. I started building some diagrams, and would like to supplement them with some code. Since I mainly use Go, this repo looks like a good fit.

## Problem
While we can export code diagrams to SVG and/or workspaces, I didn't find a way of doing it the other way around: pulling workspaces, or reading `.dsl`/`.json` files.

I would like to do two things:
- read existing diagrams -> generate Go code from them
- read existing diagrams -> generate SVG diagrams from them

## Question
Is there a way of doing that with your repo?
If not, where should I look at to get started and start working on it?

**Comment by raphael** [comment]
That's a great idea and is currently not supported. Fair warning this is probably a bit of work but the idea would be to parse the structurizr JSON into an instance of a [Workspace](https://github.com/goadesign/model/blob/master/stz/workspace.go) and from there generate the corresponding DSL. It might make sense to leverage Go templates to do that.

**Comment by tsauvajon** [comment]
It was 6 months ago, but as far as I remember I started trying to un marshal the JSON into a Workspace instance. I don't remember exactly into what issues I ran, but it was indeed more work than I anticipated, so I dropped it.

**Comment by raphael** [comment]
Happy to answer any question if you feel like taking this on again!
