### ISSUE TITLE
[Question] Person vs Actor disambiguation

### ISSUE THREAD

**Issue by danielcondemarin** [goadesign/model#27]
I started using `goadesign/model` recently, thank you for your work on this project.

The model I'm working on does not contain a "Person", as in, there is no human being involved. The reason for this is because it is a subsystem of the wider organisation architecture, that only deals with other subsystems, not people. 
A limitation I found on this project, is that I always need to define a "Person" otherwise `mdl` does not render the view on the browser. I understand that even a subsystem needs actors, as in, an entity that **interacts** with the subsystem. 
To me, it begs the question, why do we call it Person, instead of Actor ? Using the word Person is assuming a human being is interacting with your system, which is not always the case.

**Comment by raphael** [comment]
This is really a bug, it should be possible to design a model with no people in it. This is fixed inhttps://github.com/goadesign/model/pull/40.
