### ISSUE TITLE
Structurizr introduced breaking change

### ISSUE THREAD

**Issue by beffge** [goadesign/model#333]
Hi Team,
first of all: thanks for this repo and library!

I just recognised that with https://github.com/structurizr/dsl/commit/375f4574b88d5c7e484bdaaa1b311af3407393f6 a breaking change for https://github.com/goadesign/model/blob/main/mdl/deployment.go#L18 was introduced (`string` vs `int`).

Would it be possible to fix this 😅 Can I help somehow?

Regards
Horst

**Comment by raphael** [comment]
Hello, 

Thank you for bringing this up! Sounds like the field now needs to be a `*string` instead of a `*int`. Obviously, this may require other changes. It would be great if you could take a stab at it! Feel free to ask any questions here.

**Comment by raphael** [comment]
Thank you for the nice contribution. I released v1.8.0 with the change.

**Comment by beffge** [comment]
Thank you for your support!
