### ISSUE TITLE
examples do not work as expected

### ISSUE THREAD

**Issue by rvdwijngaard** [goadesign/model#4]
steps to reproduce: 
* clone the repo 
* `cd examples/basic`
* `go run main.go`

*expected result*: 
command would complete without any error

*actual result*: 
`invalid design: [model/model.go:11] missing arguments in person "User"exit status 1`

**Comment by rvdwijngaard** [comment]
I noticed this issue was introduced with commit `eb54595` 

https://github.com/goadesign/model/blob/eb54595dd12a4015df4774ff7b6df4a6938da8a8/dsl/relationship.go#L87 

Function `Uses` expects additional args to be specified.

**Comment by raphael** [comment]
Thank you for the report! The examples now all work as expected as of v1.6.3.
