### ISSUE TITLE
Missing 'order' in views

### ISSUE THREAD

**Issue by beffge** [goadesign/model#655]
Hey, it's me again 😉 

I found this: https://github.com/structurizr/examples/issues/15

Before I start a PR: Is it enough to add it to the [mdl.ViewProps](https://github.com/goadesign/model/blob/main/mdl/views.go#L109-L128)?

**Comment by raphael** [comment]
Yeah that makes sense! Thank you for looking into this.

**Comment by raphael** [comment]
Thanks for the PR!
